// Site Configuration Constants

export const siteConfig = {
  name: 'Bimo Yacht For Sale',
  description: 'Luxury Yachts for Sale & Charter in Dubai. UAE\'s premier yacht brokerage with 900K+ Instagram followers. DED Licensed.',
  url: process.env.NEXT_PUBLIC_SITE_URL || 'https://bimoyacht.com',
  ogImage: '/og-image.jpg',
  heroVideo: '/videos/hero-yacht.mp4', // Replace with your Cloudinary URL, e.g., https://res.cloudinary.com/...

  // Contact
  email: process.env.NEXT_PUBLIC_COMPANY_EMAIL || 'info@bimoyacht.com',
  phone: process.env.NEXT_PUBLIC_COMPANY_PHONE || '+971 50 156 6633',
  whatsapp: process.env.NEXT_PUBLIC_WHATSAPP_NUMBER || '971501566633',

  // Location
  address: 'Dubai Marina, Dubai, UAE',
  mapUrl: 'https://maps.google.com/?q=Dubai+Marina',

  // Social
  instagram: 'https://www.instagram.com/bimo_yacht4sale/',
  instagramHandle: '@bimo_yacht4sale',
  instagramFollowers: '900K+',
  snapchat: 'https://www.snapchat.com/@bimo_yacht4sale',
  tiktok: 'https://www.tiktok.com/@bimo_yacht4sale',
  youtube: 'https://www.youtube.com/@bimo_yacht4sale',

  // Business
  owner: 'Ebrahim',
  dedLicense: 'DED-123456',

  // SEO
  keywords: [
    'yacht for sale dubai',
    'luxury yacht dubai',
    'yacht charter dubai',
    'superyacht dubai',
    'yacht broker uae',
    'boat for sale dubai',
    'yacht rental dubai',
    'majesty yachts',
    'azimut dubai',
    'sunseeker dubai',
  ],
} as const

export const navigationLinks = [
  { href: '/', label: 'Home', labelKey: 'home' },
  { href: '/yachts', label: 'Yachts', labelKey: 'yachts' },
  { href: '/charter', label: 'Charter', labelKey: 'charter' },
  { href: '/sell-your-yacht', label: 'Sell Your Yacht', labelKey: 'sellYacht' },
  { href: '/about', label: 'About', labelKey: 'about' },
  { href: '/contact', label: 'Contact', labelKey: 'contact' },
] as const

export const yachtBrands = [
  'Abeking & Rasmussen',
  'Amels',
  'Azimut',
  'Baglietto',
  'Baltic Yachts',
  'Benetti',
  'Burger',
  'Christensen',
  'CRN',
  'Delta Marine',
  'Dominator',
  'Donzi',
  'Feadship',
  'Ferretti',
  'Fincantieri',
  'Fleming',
  'Grand Banks',
  'Gulf Craft',
  'Hatteras',
  'Heesen',
  'Horizon',
  'Jeanneau',
  'Lurssen',
  'Majesty Yachts',
  'Mangusta',
  'Mariotti',
  'Moonen',
  'Nobiskrug',
  'Nordhavn',
  'Nordic Tugs',
  'Numarine',
  'Oceanco',
  'Outer Reef',
  'Palmer Johnson',
  'Pershing',
  'Prestige',
  'Princess',
  'Riva',
  'Rossinavi',
  'Royal Huisman',
  'Sanlorenzo',
  'Silent Yachts',
  'Sunreef',
  'Sunseeker',
  'Tankoa',
  'Trinity',
  'Turquoise',
  'Viking',
  'Wally',
  'Westport',
  'Zeelander',
  'Other',
] as const

export const charterRoutes = [
  'Dubai Marina',
  'Palm Jumeirah',
  'World Islands',
  'Burj Al Arab',
  'JBR Beach',
  'Ain Dubai',
  'Atlantis',
  'Abu Dhabi',
  'Custom Route',
] as const

export const yachtAmenities = {
  en: [
    'Wi-Fi',
    'Air Conditioning',
    'Jacuzzi',
    'Swimming Platform',
    'Jet Ski',
    'Water Toys',
    'BBQ',
    'Fishing Equipment',
    'Snorkeling Gear',
    'Kayak/Paddleboard',
    'Professional Crew',
    'Gourmet Kitchen',
    'Sound System',
    'TV/Entertainment',
    'Gym Equipment',
    'Spa',
  ],
  ar: [
    'واي فاي',
    'تكييف',
    'جاكوزي',
    'منصة سباحة',
    'جت سكي',
    'ألعاب مائية',
    'شواء',
    'معدات صيد',
    'معدات غطس',
    'كاياك/لوح تجديف',
    'طاقم محترف',
    'مطبخ فاخر',
    'نظام صوتي',
    'تلفزيون/ترفيه',
    'معدات رياضية',
    'سبا',
  ],
} as const

export const trustBadges = [
  {
    icon: 'Shield',
    title: 'DED Licensed',
    titleAr: 'مرخص من دائرة التنمية الاقتصادية',
    description: 'Official Dubai business',
    descriptionAr: 'عمل رسمي في دبي',
  },
  {
    icon: 'MapPin',
    title: 'UAE Based',
    titleAr: 'مقرنا الإمارات',
    description: 'Dubai Marina HQ',
    descriptionAr: 'مقر دبي مارينا',
  },
  {
    icon: 'Instagram',
    title: '900K+ Followers',
    titleAr: '٩٠٠ ألف+ متابع',
    description: 'Trusted by thousands',
    descriptionAr: 'موثوق من الآلاف',
  },
  {
    icon: 'Award',
    title: 'Premium Service',
    titleAr: 'خدمة متميزة',
    description: 'White-glove experience',
    descriptionAr: 'تجربة فاخرة',
  },
] as const
